{
	"keywords": [
		"As seen on",
		"Buying judgments",
		"Order status",
		"Dig up dirt on friends ",
		"Additional Income",
		"Double your",
		"Earn per week ",
		"Home based",
		"Income from home",
		"Money making",
		"Opportunity ",
		"While you sleep ",
		"$$$",
		"Beneficiary",
		"Cash",
		"Cents on the dollar ",
		"Claims",
		"Cost",
		"Discount",
		"Free",
		"Hidden assets ",
		"Incredible deal",
		"Loans",
		"Money",
		"Mortgage rates ",
		"One hundred percent free ",
		"Price",
		"Quote",
		"Save big money",
		"Subject to credit",
		"Unsecured debt",
		"Accept Credit Cards",
		"Credit card offers ",
		"Investment decision ",
		"No investment",
		"Stock alert ",
		"Avoid bankruptcy",
		"Consolidate debt and credit",
		"Eliminate debt",
		"Get paid ",
		"Lower your mortgage rate",
		"Refinance home ",
		"Acceptance",
		"Chance",
		"Here",
		"Leave",
		"Maintained",
		"Never",
		"Remove",
		"Satisfaction",
		"Success",
		"Dear [email/friend/somebody] ",
		"Ad",
		"Click",
		"Click to remove ",
		"Email harvest ",
		"Increase sales ",
		"Internet market",
		"Marketing solutions ",
		"Month trial offer",
		"Notspam",
		"Open",
		"Removal instructions",
		"Search engine listings",
		"The following form",
		"Undisclosed recipient",
		"We hate spam ",
		"Cures baldness ",
		"Human growth hormone",
		"Lose weight spam ",
		"Online pharmacy ",
		"Stop snoring ",
		"Vicodin",
		"#1",
		"4U",
		"Billion dollars ",
		"Million",
		"Being a member",
		"Cannot be combined with any other offer ",
		"Financial freedom ",
		"Guarantee ",
		"Important information regarding",
		"Mail in order form ",
		"Nigerian ",
		"No claim forms ",
		"No gimmick ",
		"No obligation",
		"No selling",
		"Not intended ",
		"Offer",
		"Priority mail",
		"Produced and sent out ",
		"Stuff on sale",
		"They're just giving it away",
		"Unsolicited",
		"Warranty",
		"What are you waiting for? ",
		"Winner ",
		"You are a winner!",
		"Cancel at any time ",
		"Get",
		"Print out and fax ",
		"Free",
		"Free consultation ",
		"Free grant money",
		"Free Instant",
		"Free membership ",
		"Free preview ",
		"Free sample ",
		"All natural",
		"Certified",
		"Fantastic deal ",
		"It's effective",
		"Real thing",
		"Access",
		"Apply Online ",
		"Can't live without",
		"Don't hesitate",
		"For you",
		"Great offer ",
		"Instant",
		"Now",
		"Once in lifetime ",
		"Order now",
		"Special promotion ",
		"Time limited",
		"Addresses on CD",
		"Brand new pager ",
		"Celebrity",
		"Legal",
		"Phone",
		"Buy",
		"Clearance",
		"Orders shipped by",
		"Meet singles ",
		"Be your own boss",
		"Earn $",
		"Expect to earn ",
		"Home employment",
		"Make $",
		"Online biz opportunity",
		"Potential earnings ",
		"Work at home ",
		"Affordable",
		"Best price",
		"Cash bonus ",
		"Cheap",
		"Collect",
		"Credit",
		"Earn",
		"Fast cash",
		"hidden charges",
		"Insurance ",
		"Lowest price ",
		"Money back",
		"No cost",
		"Only $ ",
		"Profits ",
		"Refinance",
		"Save up to",
		"They keep your money -- no refund! ",
		"US dollars",
		"Cards accepted",
		"Explode your business",
		"No credit check ",
		"Requires initial investment",
		"Stock disclaimer statement ",
		"Calling creditors",
		"Consolidate your debt",
		"Financially independent",
		"Lower interest rate",
		"Lowest insurance rates",
		"Social security number ",
		"Accordingly",
		"Dormant",
		"Hidden",
		"Lifetime",
		"Medium",
		"Passwords",
		"Reverses",
		"Solution",
		"Teen",
		"Friend",
		"Auto email removal ",
		"Click below",
		"Direct email ",
		"Email marketing ",
		"Increase traffic ",
		"Internet marketing",
		"Mass email ",
		"More Internet Traffic",
		"One time mailing ",
		"Opt in",
		"Sale",
		"Search engines",
		"This isn't junk ",
		"Unsubscribe",
		"Web traffic",
		"Diagnostics",
		"Life Insurance",
		"Medicine",
		"Removes wrinkles",
		"Valium",
		"Weight loss",
		"100% free",
		"50% off",
		"Join millions",
		"One hundred percent guaranteed ",
		"Billing address ",
		"Confidentially on all orders ",
		"Gift certificate",
		"Have you been turned down? ",
		"In accordance with laws",
		"Message contains",
		"No age restrictions ",
		"No disappointment ",
		"No inventory ",
		"No purchase necessary",
		"No strings attached",
		"Obligation",
		"Per day",
		"Prize",
		"Reserves the right",
		"Terms and conditions",
		"Trial",
		"Vacation",
		"We honor all ",
		"Who really wins? ",
		"Winning ",
		"You have been selected ",
		"Compare",
		"Give it away",
		"See for yourself",
		"Free access ",
		"Free DVD ",
		"Free hosting",
		"Free investment ",
		"Free money ",
		"Free priority mail ",
		"Free trial ",
		"All new",
		"Congratulations ",
		"For free ",
		"Outstanding values ",
		"Risk free",
		"Act Now!",
		"Call free ",
		"Do it today",
		"For instant access ",
		"Get it now",
		"Info you requested",
		"limited time",
		"Now only",
		"One time",
		"Order today",
		"Supplies are limited",
		"Urgent",
		"Beverage",
		"Cable converter ",
		"Copy DVDs ",
		"Luxury car ",
		"Rolex",
		"Buy direct",
		"Order",
		"shopper",
		"Score with babes",
		"Compete for your business",
		"Earn extra cash",
		"Extra income",
		"Homebased business",
		"Make money",
		"Online degree",
		"University diplomas",
		"Work from home",
		"Bargain",
		"Big bucks ",
		"Cashcashcash",
		"Check",
		"Compare rates",
		"Credit bureaus ",
		"Easy terms ",
		"For just $XXX",
		"Income",
		"Investment",
		"Million dollars",
		"Mortgage",
		"No fees ",
		"Pennies a day ",
		"Pure profit",
		"Save $",
		"Serious cash",
		"Unsecured credit",
		"Why pay more? ",
		"Check or money order ",
		"Full refund ",
		"No hidden Costs",
		"Sent in compliance",
		"Stock pick ",
		"Collect child support",
		"Eliminate bad credit ",
		"Get out of debt",
		"Lower monthly payment ",
		"Pre-approved",
		"Your income",
		"Avoid",
		"Freedom",
		"Home",
		"Lose",
		"Miracle",
		"Problem",
		"Sample",
		"Stop",
		"Wife",
		"Hello",
		"Bulk email",
		"Click here",
		"Direct marketing ",
		"Form",
		"Increase your sales",
		"Marketing",
		"Member",
		"Multi level marketing",
		"Online marketing",
		"Performance",
		"Sales",
		"Subscribe",
		"This isn't spam ",
		"Visit our website",
		"Will not believe your eyes ",
		"Fast Viagra delivery",
		"Lose weight",
		"No medical exams",
		"Reverses aging",
		"Viagra",
		"Xanax",
		"100% Satisfied",
		"Billion",
		"Join millions of Americans ",
		"Thousands",
		"Call",
		"Deal",
		"Giving away",
		"If only it were that easy",
		"Long distance phone offer",
		"Name brand ",
		"No catch ",
		"No experience ",
		"No middleman",
		"No questions asked",
		"No-obligation",
		"Off shore",
		"Per week",
		"Prizes",
		"Shopping spree ",
		"The best rates",
		"unlimited",
		"Vacation offers",
		"Weekend getaway ",
		"Win",
		"won",
		"You're a Winner!",
		"Copy accurately ",
		"Print form signature",
		"Sign up free today ",
		"Free cell phone ",
		"Free gift",
		"Free installation ",
		"Free leads ",
		"Free offer ",
		"Free quote ",
		"Free website ",
		"Amazing ",
		"Drastically reduced ",
		"Guaranteed",
		"Promise you",
		"Satisfaction guaranteed ",
		"Apply now",
		"Call now ",
		"Don't delete ",
		"For Only",
		"Get started now ",
		"Information you requested",
		"New customers only ",
		"Offer expires ",
		"Only",
		"Please read ",
		"Take action now",
		"While supplies last ",
		"Bonus",
		"Casino ",
		"Laser printer ",
		"New domain extensions ",
		"Stainless steel",
		"help"
	]
}